apiVersion: v1
kind: Service
metadata:
  name: youtube-clone-service
spec:
  selector:
    app: youtube-clone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
